hyperledger-identus/cloud-agent

prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/PrismAgentApp.scala
prism-agent/service/server/src/test/scala/io/iohk/atala/api/util/Tapir2StaticOAS.scala

This ensures the list of endpoints used as input to the Tapir2StaticOAS tool is the same as the one used by the agent at runtime.

chore: use the agent endpoint declarations in Tapir2StaticOAS

---

prism-agent/service/server/src/main/scala/io/iohk/atala/api/http/codec/DIDCodec.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/castor/controller/DIDEndpoints.scala

Fixes ATL-5198
Previous PR #616 make the OAS document more accurate, but it broke the content negotiation of the resolution. This PR make the content negotiation work again.

fix(prism-agent): make resolve did representation content type work

---

connect/lib/core/src/main/scala/io/iohk/atala/connect/core/model/error/ConnectionServiceError.scala
connect/lib/core/src/main/scala/io/iohk/atala/connect/core/service/ConnectionService.scala
connect/lib/core/src/main/scala/io/iohk/atala/connect/core/service/ConnectionServiceImpl.scala
connect/lib/core/src/main/scala/io/iohk/atala/connect/core/service/ConnectionServiceNotifier.scala
connect/lib/core/src/main/scala/io/iohk/atala/connect/core/service/MockConnectionService.scala
connect/lib/core/src/test/scala/io/iohk/atala/connect/core/service/ConnectionServiceImplSpec.scala
connect/lib/core/src/test/scala/io/iohk/atala/connect/core/service/ConnectionServiceNotifierSpec.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/DidCommHttpServer.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/jobs/ConnectBackgroundJobs.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/connect/controller/ConnectionController.scala

The Invitee will check the invitation expiry against the configured expiration time, If the message is received within the expiration time the connection request will be accepted, If the connection request message is received after the expiration time it will update the state of the Invitation to Invitation Expired. 
On the Invitee side since it is did comm message the Invitee will try the same message until configured max retries.
Since we have not implemented ReportProblem in Connect Protocol we will need accept this behaviour for now
Fixes ATL-5436

fix(prism-agent): update invitation expiration on connection request

---

build.sbt

Changes private SDK 1.4 dependency to public maven central
One version of PRISM SDK 1.4 is now publicly available on Maven Central:
https://central.sonatype.com/artifact/io.iohk.atala
This removes the last private dependency for the repository.

fix: change private sdk 1.4 to public maven

---

build.sbt
prism-agent/service/server/src/main/resources/application.conf
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/notification/WebhookPublisher.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/PrismAgentApp.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/config/AppConfig.scala
prism-agent/service/server/src/test/scala/io/iohk/atala/agent/server/AgentInitializationSpec.scala
prism-agent/service/wallet-api/src/main/scala/io/iohk/atala/agent/walletapi/model/Entity.scala

Fixes ATL-5698
Refine webhook and default wallet behavior
- `GLOBAL_WEBHOOK_` for configurations of global webhook (all wallets)
- `DEFAULT_WALLET_` for configurations of default wallet and automatically create one if not exist (seed, webhook, auth)

fix(prism-agent): refine default wallet and webhook configuration behavior

---

prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/PrismAgentApp.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/castor/controller/DIDRegistrarEndpoints.scala
prism-agent/service/server/src/test/scala/io/iohk/atala/agent/server/AgentInitializationSpec.scala

We start to have environment variables that shouldn't work in some permutation. It is slightly confusing to user when those are conflicting each other. This PR add some sanity check for the config and stops the Agent from starting with an error message.

fix(prism-agent): validate application config during startup

---

connect/lib/sql-doobie/src/main/scala/io/iohk/atala/connect/sql/repository/Migrations.scala
pollux/lib/sql-doobie/src/main/scala/io/iohk/atala/pollux/sql/repository/Migrations.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/Main.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/sql/Migrations.scala

Add a step to execute some SQL statement to refine privileges for db app user. 
DB application user provisioned by k8s operator doesn't have the right permission for RLS feature.

fix(prism-agent): define db app user privileges before app starts

---

.github/workflows/e2e-tests.yml
infrastructure/local/run.sh
infrastructure/shared/apisix/conf/apisix.yaml
infrastructure/shared/docker-compose-demo.yml
infrastructure/shared/docker-compose.yml

On the integration of the local scripts with the quick started guide the didcomm service needs to be exposed and reachable by the browser and mobile platforms. (allowing cors and connections from outside of the docker network.)
Fixes [ATL-5805](https://input-output.atlassian.net/browse/ATL-5805)
* [*] Improvements (misc. changes to existing features)
* [ *] are not breaking changes
* [*] If yes to above: I have updated the documentation accordingly

fix: Adding localhost environment variable in run.sh script for local development

---

prism-agent/service/server/src/main/scala/io/iohk/atala/iam/authentication/apikey/ApiKeyAuthenticatorImpl.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/iam/authentication/apikey/AuthenticationRepository.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/iam/authentication/apikey/JdbcAuthenticationRepository.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/iam/entity/http/model/ApiKeyAuthenticationRequest.scala
prism-agent/service/server/src/test/scala/io/iohk/atala/iam/authentication/apikey/ApiKeyAuthenticatorSpec.scala
prism-agent/service/server/src/test/scala/io/iohk/atala/iam/authentication/apikey/JdbcAuthenticationRepositorySpec.scala
prism-agent/service/wallet-api/src/main/resources/sql/agent/V13__apikey_authentication_improvements.sql
tests/e2e-tests/src/test/kotlin/common/Environments.kt
tests/e2e-tests/src/test/kotlin/features/multitenancy/EntitySteps.kt

Code cleanup
APIKEY logic doesn't allow to use the same apikey
Fixes ATL-5768

fix: prohibit tenants to use equal api keys

---

docs/docusaurus/credentialdefinition/create.md
docs/docusaurus/credentialdefinition/credential-definition.md
docs/docusaurus/credentialdefinition/delete.md
docs/docusaurus/schemas/credential-schema.md
docs/docusaurus/sidebars.js

Fixes https://input-output.atlassian.net/browse/ATL-5851

docs: add credential definition docs

---

prism-agent/service/server/src/main/resources/application.conf
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/DidCommHttpServer.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/Main.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/PrismAgentApp.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/config/AppConfig.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/connect/controller/ConnectionControllerImpl.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/issue/controller/IssueControllerImpl.scala

fix(prism-agent): agent should read DIDComm port from config

---

docs/docusaurus/credentials/issue.md

Replacing a broken link in documentation which is breaking the docs CI build due to an invalid link.
Fixes https://input-output.atlassian.net/browse/ATL-5875 CI task from not being able to complete.

docs: replace broken link in Issue.md, AnonCreds Credential definition

---

README.md
infrastructure/shared/docker-compose-demo.yml
tests/integration-tests/src/main/kotlin/models/AnoncredsSchema.kt
tests/integration-tests/src/main/kotlin/models/JsonSchema.kt
tests/integration-tests/src/main/kotlin/models/JsonSchemaProperty.kt
tests/integration-tests/src/test/kotlin/common/TestConstants.kt
tests/integration-tests/src/test/kotlin/features/CommonSteps.kt
tests/integration-tests/src/test/kotlin/features/credentials/IssueCredentialsSteps.kt
tests/integration-tests/src/test/kotlin/features/schemas/CredentialSchemasSteps.kt
tests/integration-tests/src/test/resources/features/credentials/issue_credentials.feature

Adds an integration test for anoncreds issuance

test: add anoncreds issuance happy path bdd scenario

---

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/serdes/AnoncredPresentationRequestSchemaSerDesV1.scala
pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/serdes/AnoncredPresentationRequestSchemaSerDesSpec.scala
pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/serdes/PublicCredentialDefinitionSchemaSerDesSpec.scala

Fixes https://input-output.atlassian.net/browse/ATL-5966

feat: add serdeser for anoncred presentation request

---

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/error/PresentationError.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/schema/validator/SchemaSerDes.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/MockPresentationService.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/PresentationService.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/PresentationServiceImpl.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/PresentationServiceNotifier.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/serdes/AnoncredPresentationRequestV1.scala
pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/PresentationServiceNotifierSpec.scala
pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/PresentationServiceSpec.scala
pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/PresentationServiceSpecHelper.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/presentproof/controller/PresentProofController.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/presentproof/controller/PresentProofControllerImpl.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/presentproof/controller/http/RequestPresentationInput.scala

Fixes https://input-output.atlassian.net/browse/ATL-5966

feat: Create/Store presentation proof request

---

connect/lib/sql-doobie/src/main/scala/io/iohk/atala/connect/sql/repository/Migrations.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/MockCredentialService.scala
pollux/lib/sql-doobie/src/main/scala/io/iohk/atala/pollux/sql/repository/Migrations.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/Main.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/Modules.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/http/ZHttpEndpoints.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/sql/Migrations.scala

Fixes ATL-5793. Check for active RLS after running migration and fail during startup if RLS is not active.

fix: check for active RLS on db application user

---

prism-agent/service/server/src/main/scala/io/iohk/atala/iam/authentication/oidc/KeycloakClient.scala

When making a request where Basic auth credential contains special character, it will fail with invalid credential. Credential should be encoded before sending.

fix(prism-agent): perform percent encoding on auth header for token introspection request

---

pollux/lib/sql-doobie/src/main/resources/sql/pollux/V16__revocation_status_lists_table_and_columns.sql

fix migration V16 by altering a data type `issue_credential_record_id` in `credentials_in_status_list` from UUID to varchar(64)

fix(pollux): V16 migration is failing to add FK constraint because of type mismatch

---

castor/lib/core/src/main/scala/io/iohk/atala/castor/core/util/DIDOperationValidator.scala
castor/lib/core/src/test/scala/io/iohk/atala/castor/core/util/DIDOperationValidatorSpec.scala
infrastructure/charts/agent/templates/deployment.yaml
infrastructure/charts/agent/templates/postgresql.yaml
infrastructure/charts/agent/values.yaml
infrastructure/ci/docker-compose-multiple-actors.yml
infrastructure/shared/docker-compose-demo.yml
infrastructure/shared/docker-compose-mt-keycloak.yml
infrastructure/shared/docker-compose.yml
infrastructure/single-tenant-testing-stack/docker-compose.yml
prism-agent/service/server/src/main/resources/application.conf
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/config/AppConfig.scala

Partially fixes ATL-5374. Clean up some warning from sonarcloud analysis and remove unused configurations.

chore(castor): clean up sonarcloud issues and unused configurations

---

connect/lib/core/src/main/scala/io/iohk/atala/connect/core/model/ConnectionRecord.scala
connect/lib/core/src/main/scala/io/iohk/atala/connect/core/service/ConnectionService.scala
connect/lib/core/src/main/scala/io/iohk/atala/connect/core/service/ConnectionServiceImpl.scala
connect/lib/core/src/main/scala/io/iohk/atala/connect/core/service/ConnectionServiceNotifier.scala
connect/lib/core/src/main/scala/io/iohk/atala/connect/core/service/MockConnectionService.scala
connect/lib/core/src/test/scala/io/iohk/atala/connect/core/repository/ConnectionRepositorySpecSuite.scala
connect/lib/core/src/test/scala/io/iohk/atala/connect/core/service/ConnectionServiceImplSpec.scala
connect/lib/core/src/test/scala/io/iohk/atala/connect/core/service/ConnectionServiceNotifierSpec.scala
connect/lib/sql-doobie/src/main/resources/sql/connect/V7__add_goal_and_goal_code.sql
connect/lib/sql-doobie/src/main/scala/io/iohk/atala/connect/sql/repository/JdbcConnectionRepository.scala
mercury/mercury-library/agent/src/main/scala/io/iohk/atala/mercury/InvitationPrograms.scala
mercury/mercury-library/protocol-connection/src/main/scala/io/iohk/atala/mercury/protocol/connection/ConnectionInvitation.scala
mercury/mercury-library/protocol-connection/src/main/scala/io/iohk/atala/mercury/protocol/connection/ConnectionRequest.scala
mercury/mercury-library/protocol-invitation/src/main/scala/io/iohk/atala/mercury/protocol/invitation/v2/Invitation.scala
mercury/mercury-library/protocol-invitation/src/test/scala/io/iohk/atala/mercury/protocol/invitation/v2/OutOfBandSpec.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/jobs/ConnectBackgroundJobs.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/connect/controller/ConnectionControllerImpl.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/connect/controller/http/Connection.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/connect/controller/http/CreateConnectionRequest.scala

Accept goal and goal code to create a connection invitation 
Fixes ATL-3320

feat: Accept goal and goalCode to create connection invitation 

---

prism-agent/service/server/src/main/scala/io/iohk/atala/iam/authentication/SecurityLogic.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/iam/wallet/http/controller/WalletManagementController.scala
prism-agent/service/server/src/test/scala/io/iohk/atala/iam/authentication/SecurityLogicSpec.scala

ATL-6210
ATL-6211
- AdminApiKey have the highest priority
- Improve auth error message by excluding `MethodNotEnabled`

fix: change admin auth priority and improve auth error message

---

infrastructure/charts/agent/templates/deployment.yaml
infrastructure/charts/agent/templates/postgresql.yaml
infrastructure/charts/agent/values.yaml

Adding option to specify nodeAffinity, tolerations, and resources for prism-agent deployment and postgresql objects which will allows us to schedule pods to dedicated nodepools using these parameters.
Examples are provided in `values.yaml`
Fixes ATL-5538

feat: add nodeAffinity, tolerations, and resources to k8s deployment

---

prism-agent/service/server/src/main/resources/application.conf
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/Modules.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/config/AppConfig.scala

Previously, connecting to PRISM Node over gRPC was hardcoded to be insecure and over plaintext
Now, the default is still insecure but can be configured at run time with an environment variable
In future - this should be made secure by default but would be a breaking change and needs to be managed as such

feat: add configuration for gRPC usePlainText (enable TLS for gRPC)

---

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/CredentialServiceImpl.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/PresentationServiceImpl.scala

Fixes https://input-output.atlassian.net/browse/ATL-6305

fix: Fix Anoncred Issuance Processing

---

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/schema/CredentialSchema.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/CredentialDefinitionServiceImpl.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/PresentationServiceImpl.scala
pollux/lib/core/src/test/resources/anoncred-presentation-schema-example.json
pollux/lib/core/src/test/resources/anoncred-schema-example.json
pollux/lib/core/src/test/resources/vc-schema-example.json
prism-agent/service/server/src/test/resources/anoncred-schema-example.json
prism-agent/service/server/src/test/resources/vc-schema-example.json
tests/integration-tests/src/test/kotlin/features/credentials/IssueCredentialsSteps.kt

fix(prism-agent): fix credential schema parsing as spec

---

.github/workflows/pr-lint.yml

Pin the 'action-semantic-pull-request' plugin version to 5.2.0 to force node v16 usage.

ci: pin the 'action-semantic-pull-request' plugin version to 5.2.0 

---

build.sbt
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/schema/type/CredentialJsonSchemaSerDesV1.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/schema/type/CredentialJsonSchemaType.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/schema/validator/JsonSchemaUtils.scala
pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/model/schema/AnoncredSchemaTypeSpec.scala
pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/model/schema/CredentialSchemaSpec.scala
prism-agent/service/server/src/test/scala/io/iohk/atala/pollux/schema/CredentialSchemaAnoncredSpec.scala
prism-agent/service/server/src/test/scala/io/iohk/atala/pollux/schema/CredentialSchemaBasicSpec.scala
prism-agent/service/server/src/test/scala/io/iohk/atala/pollux/schema/CredentialSchemaMultiTenancySpec.scala
prism-agent/service/server/src/test/scala/io/iohk/atala/pollux/schema/CredentialSchemaTestTools.scala
tests/integration-tests/src/main/kotlin/models/JsonSchema.kt

Fixes [ATL-4842](https://input-output.atlassian.net/browse/ATL-4842)

feat(pollux): add Json VC schema meta validation

---

prism-agent/service/server/src/main/scala/io/iohk/atala/api/http/codec/DIDCodec.scala

Update tapir definition so that it doesn't render this
```
type: string
format: binary
```

fix: remove oas schema format for empty repsonse body

---

prism-agent/service/server/src/main/resources/application.conf

Make the Postgresql connection pool size configurable and reduce the default number from 8 to 4

feat(agent): make the connection pool size configurable, fixes #913

---

tests/integration-tests/build.gradle.kts
tests/integration-tests/src/test/kotlin/features/verificationpolicies/VerificationPoliciesSteps.kt

Fixes Integration test by fixing breaking changes introduce VerificationPolicy api

fix: integration test

---

docs/docusaurus/secrets/operation.md
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/CredentialDefinitionServiceImpl.scala
prism-agent/service/server/src/main/resources/application.conf
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/Modules.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/config/AppConfig.scala
prism-agent/service/server/src/test/scala/io/iohk/atala/agent/server/AgentInitializationSpec.scala
prism-agent/service/server/src/test/scala/io/iohk/atala/agent/server/config/AppConfigSpec.scala
prism-agent/service/wallet-api/src/main/scala/io/iohk/atala/agent/walletapi/vault/VaultClient.scala
prism-agent/service/wallet-api/src/main/scala/io/iohk/atala/agent/walletapi/vault/VaultDIDSecretStorage.scala
prism-agent/service/wallet-api/src/main/scala/io/iohk/atala/agent/walletapi/vault/VaultGenericSecretStorage.scala
prism-agent/service/wallet-api/src/main/scala/io/iohk/atala/agent/walletapi/vault/package.scala
prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/benchmark/KeyDerivation.scala
prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/service/ManagedDIDServiceSpec.scala
prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/service/WalletManagementServiceSpec.scala
prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/storage/DIDSecretStorageSpec.scala
prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/storage/GenericSecretStorageSpec.scala
prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/storage/WalletSecretStorageSpec.scala
prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/test/container/VaultLayer.scala
prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/test/container/VaultTestContainerSupport.scala
shared-test/src/test/scala/io/iohk/atala/sharedtest/containers/VaultContainerCustom.scala
shared-test/src/test/scala/io/iohk/atala/sharedtest/containers/VaultTestContainer.scala

Support config `VAULT_USE_SEMANTIC_PATH=false` to opt-out from using meaningful secret path for a fixed-length secret path. The path hierarchy is cut-off at certain depth and replaced by sha256 hash of path relative to the cut-off. The original path is stored in `semanticPath` key of the secret `custom_metadata` 
Fixes https://github.com/hyperledger-labs/open-enterprise-agent/issues/908

fix: allow configurable path convention for vault secrets

---

prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/http/DocModels.scala

Fixes [ATL-6321](https://input-output.atlassian.net/browse/ATL-6321)

docs(prism-agent): remove `termsOfService` from OAS

---

prism-agent/service/server/src/main/scala/io/iohk/atala/presentproof/controller/http/PresentationStatus.scala

[ATL-6812](https://input-output.atlassian.net/browse/ATL-6812)

fix(prism-agent): add missing 'PresentationVerificationFailed' status to REST API response enum

---

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/verification/VcVerificationServiceImpl.scala
pollux/lib/vc-jwt/src/main/scala/io/iohk/atala/pollux/vc/jwt/JWTVerification.scala
pollux/lib/vc-jwt/src/main/scala/io/iohk/atala/pollux/vc/jwt/VerifiableCredentialPayload.scala

https://input-output.atlassian.net/browse/ATL-6787
https://input-output.atlassian.net/browse/ATL-6779

feat: VC Verification API Algorithm Issuer Verification

---

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/verification/VcVerificationService.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/verification/VcVerificationServiceImpl.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/PrismAgentApp.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/VcVerificationControllerImpl.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/ParameterizableVcVerification.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerification.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerificationParameter.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerificationRequest.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerificationResponse.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerificationResult.scala

https://input-output.atlassian.net/browse/ATL-6913

feat: support parameter

---

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/verification/VcVerification.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/verification/VcVerificationService.scala
pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/verification/VcVerificationServiceImpl.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/VcVerificationControllerImpl.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerification.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerificationParameter.scala
prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerificationRequest.scala

https://input-output.atlassian.net/browse/ATL-6782

feat: VC Verification  Audiance check

---

.github/workflows/integration-tests.yml
.github/workflows/performance-tests.yml

move away from `node{12,16}`-based actions as they have been deprecated

chore: bump integration and performance test actions

---

tests/integration-tests/src/test/kotlin/config/services/Agent.kt

ci: integration test startup fail workaround

---

.github/workflows/labeler.yml

ci: update labeler permissions

---

.github/workflows/release.yml

ci: use github.actor in the release workflow

---

README.md

chore: update Coveralls badge [skip ci]

---

pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/oid4vci/CredentialConfiguration.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/oid4vci/CredentialIssuer.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/repository/OID4VCIIssuerMetadataRepositorySpecSuite.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/OID4VCIIssuerMetadataServiceSpecSuite.scala
pollux/sql-doobie/src/test/scala/org/hyperledger/identus/pollux/core/service/OID4VCIIssuerMetadataServiceSpec.scala
pollux/sql-doobie/src/test/scala/org/hyperledger/identus/pollux/sql/repository/JdbcOID4VCIIssuerMetadataRepositorySpec.scala

test: add tests for oid4vci credential configuration CRUD

---

README.md

After move from IO to Hyperledger organisation and renaming from PRISM agent to Cloud Agent, the Docker packages location was broken. It appears that there are two locations now. So this patch is to update the links in the README file. 
Note that I am not sure if in the end the packages before v1.31.0 will be all moved to the Hyperledger organisation.

fix: broken link for the cloud agent packages in readme file

---

.github/workflows/release-clients.yml
cloud-agent/client/generator/publish-clients.sh
cloud-agent/client/typescript/package.json

- changed the tag to dispatch the workflow
- use GITHUB_TOKEN to publish ts package to ghcr.io

ci: fix the publishing of ts client [skip ci]

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/CredentialIssuerEndpoints.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/CredentialIssuerServerEndpoints.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/controller/CredentialIssuerController.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/service/OIDCCredentialIssuerService.scala
examples/.nickel/versions.ncl
examples/mt-keycloak-vault/compose.yaml
examples/mt-keycloak/compose.yaml
examples/mt/compose.yaml
examples/st-multi/compose.yaml
examples/st-oid4vci/compose.yaml
examples/st-oid4vci/demo.py
examples/st-vault/compose.yaml
examples/st/compose.yaml

Update local script to consume metadata endpoint in the issuance flow. Next, we need to integrate this metadata to `credential` and `credential_offer` endpoint to make this fully functional.

chore: update OID4VCI example script to use issuer metadata

---

.github/workflows/scala-steward.yml
.scala-steward.conf
README.md

- change Scala Steward to sign the commits as the Hyperledger Bot
- limit the number of updates in each PR to 10
- add Scala Steward badge to the README.md

ci: switch Scala Steward to make the PRs as the hyperledger-bot

---

castor/src/main/scala/org/hyperledger/identus/castor/core/model/error/package.scala
castor/src/main/scala/org/hyperledger/identus/castor/core/util/DIDOperationValidator.scala
castor/src/test/scala/org/hyperledger/identus/castor/core/util/DIDOperationValidatorSpec.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/controller/http/ManagedDID.scala
pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/DidJWT.scala

Expose ability to select key types when creating / updating managed DID. This will soon be released in order to publish the TS and Kotlin client for integration testing. Also add minor alignment on the DID operation validation with Node.

fix: expose new key types in rest api

---

package.json

When there are multiple `prerelease/*` branch, the release task will fail as the prerelease version must be unique. This PR added the branch to the prerelease tag so it has this versioning `<version>-snapshot.<branch>.<n>`

ci: use branch name in pre-release version name

---

.github/workflows/lint.yml

- fix the megalinter flow to fail the build when the errors found and auto-fixes are applied

ci: fail the build when the megalinter found the issues [skip ci]

---

README.md

- As the site Identus is available, replace the old atalaprism.io by it.
- Correct a grammar mistake.
- Other minor changes.

docs: update website link to Identus

---

infrastructure/charts/agent/Chart.yaml
infrastructure/charts/agent/templates/_helpers.tpl
infrastructure/charts/agent/templates/apisixroute.yaml
infrastructure/charts/agent/templates/apisixtls.yaml
infrastructure/charts/agent/templates/certificate.yaml
infrastructure/charts/agent/templates/configmap.yaml
infrastructure/charts/agent/templates/deployment.yaml
infrastructure/charts/agent/templates/postgresql.yaml
infrastructure/charts/agent/templates/service.yaml
infrastructure/charts/agent/values.yaml

feat: Rename helm chart and its resources

---

.mega-linter.yml
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/CredentialIssuerEndpoints.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/CredentialIssuerServerEndpoints.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/controller/CredentialIssuerController.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/domain/IssuanceSession.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/http/CredentialOfferRequest.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/http/IssuerMetadata.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/service/OIDCCredentialIssuerService.scala
examples/.nickel/versions.ncl
examples/mt-keycloak-vault/compose.yaml
examples/mt-keycloak/compose.yaml
examples/mt/compose.yaml
examples/st-multi/compose.yaml
examples/st-oid4vci/compose.yaml
examples/st-oid4vci/demo.py
examples/st-vault/compose.yaml
examples/st/compose.yaml
extensions/keycloak-oid4vci/src/main/java/io/iohk/atala/keycloak/OID4VCITokenEndpoint.java

Glue the issuer metadata to the credential issuer endpoint so we can proceed with the `nonce` and JWT proof.

fix: integrate issuer metadata in oid4vci credential endpoint

---

.github/workflows/deployment.yml
.github/workflows/ff-merge.yml
.github/workflows/labeler.yml
.github/workflows/unit-tests.yml

- self-hosted runners of the GitHub actions are replaced with the GitHub runners ubuntu-latest

ci: switch to the GitHub runners

---

.github/workflows/deployment.yml
.github/workflows/ff-merge.yml
.github/workflows/labeler.yml
.github/workflows/unit-tests.yml

This reverts commit efba1aac0be8bfdb73cbc11cdd0cc0d0aa283aea.
This this PR https://github.com/hyperledger/identus-cloud-agent/pull/1121, we switch to `ubuntu-latest` because our `self-hosted` were offline. Now we have our runners online, we should switch back since the CI job took much longer to execute.
- took 26m on `ubuntu-latest` https://github.com/hyperledger/identus-cloud-agent/actions/runs/9317151746
- took 16m on `self-hosted` https://github.com/hyperledger/identus-cloud-agent/actions/runs/9283779143
Link to existing ADR (Architecture Decision Record), if any. If relevant, describe other approaches explored and the selected approach. Documenting why the methods were not selected will create a knowledge base for future reference, helping prevent others from revisiting less optimal …

ci: revert switch to the GitHub runners

---

examples/.nickel/stack.ncl
examples/.nickel/versions.ncl
examples/mt-keycloak-vault/compose.yaml
examples/mt-keycloak/compose.yaml
examples/mt/compose.yaml
examples/st-multi/compose.yaml
examples/st-oid4vci/compose.yaml
examples/st-vault/compose.yaml
examples/st/compose.yaml

fix: make oidc local script work

---

cloud-agent/service/server/src/main/resources/application.conf
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/config/AppConfig.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/IssueBackgroundJobs.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceNotifier.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/MockCredentialService.scala
pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/DidJWT.scala

This PR allows the expiration time for the Agent (Role Issuer) to be configurable.
The expiration time for SD JWT credentials can also be set when the Issuer makes a credential offer, including other claims in the exp field.
If the exp field is present, its value takes precedence over the configurable value.
The value in the exp field must be specified in Unix epoch seconds.
For more details, refer to [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519#page-9).
"claims": {
......
"exp" : 1618244393 
}

fix: Add expiration time for cloud-agent

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialschema/SchemaRegistryServerEndpoints.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialschema/controller/CredentialSchemaController.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialschema/controller/CredentialSchemaControllerImpl.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialschema/controller/CredentialSchemaControllerLogic.scala
cloud-agent/service/server/src/test/scala/org/hyperledger/identus/pollux/schema/CredentialSchemaAnoncredSpec.scala
cloud-agent/service/server/src/test/scala/org/hyperledger/identus/pollux/schema/CredentialSchemaMultiTenancySpec.scala
cloud-agent/service/server/src/test/scala/org/hyperledger/identus/pollux/schema/CredentialSchemaTestTools.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/schema/CredentialDefinition.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/schema/CredentialSchema.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/repository/CredentialDefinitionRepositoryInMemory.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/repository/CredentialSchemaRepository.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/repository/repository.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialDefinitionServiceImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialSchemaService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialSchemaServiceImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/verification/CredentialSchemaServiceError.scala
pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/JdbcCredentialDefinitionRepository.scala
pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/JdbcCredentialSchemaRepository.scala

https://input-output.atlassian.net/browse/ATL-6828

fix: Schema Error Handling

---

docs/decisions/20230516-hierarchical-deterministic-key-generation-algorithm.md

Updating the ADR to reflect the recent changes in bip32 derivation. 
Mainly, secp256k1 stays the same.
We introduce now HDKeys for Ed25519, those will be using  different bip32 implementation.
The ADR changes are to reflect this but no more changes have been done to the derivationPath specification.
Requires no cloud agent changes as that is already implemented.

docs: updating the hdkey ADR  [skip ci] 

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialdefinition/controller/CredentialDefinitionController.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialdefinition/controller/CredentialDefinitionControllerImpl.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialschema/controller/CredentialSchemaController.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialschema/controller/CredentialSchemaControllerImpl.scala
cloud-agent/service/server/src/test/scala/org/hyperledger/identus/pollux/credentialdefinition/CredentialDefinitionTestTools.scala
cloud-agent/service/server/src/test/scala/org/hyperledger/identus/pollux/schema/CredentialSchemaAnoncredSpec.scala
cloud-agent/service/server/src/test/scala/org/hyperledger/identus/pollux/schema/CredentialSchemaMultiTenancySpec.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/repository/CredentialDefinitionRepository.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/repository/CredentialDefinitionRepositoryInMemory.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialDefinitionService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialDefinitionServiceError.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialDefinitionServiceImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialSchemaService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialSchemaServiceError.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialSchemaServiceImpl.scala
pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/JdbcCredentialDefinitionRepository.scala

https://input-output.atlassian.net/browse/ATL-7219

fix: Credential Defintion Error Handling Part 2

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/controller/CredentialIssuerController.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/http/CredentialIssuer.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/repository/OID4VCIIssuerMetadataRepository.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/OID4VCIIssuerMetadataService.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/repository/OID4VCIIssuerMetadataRepositorySpecSuite.scala
pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/JdbcOID4VCIIssuerMetadataRepository.scala

`CredentialIssuer` update api should have parity with the create model. Added a `client_id` and `client_secret` patch. 

fix: update issuer auth server model parity

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/BackgroundJobsHelper.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImpl.scala

In integration-test, we start to create multiple key types inside the DID document. This result in flaky test since the way we pick key is not filtered by key types, so sometime we pick the wrong key and fail the test. 
https://github.com/hyperledger/identus-cloud-agent/actions/runs/9414449925

fix: pick right key type when creating corresponding issuer

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/PresentBackgroundJobs.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/MockPresentationService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceNotifier.scala
pollux/sd-jwt/src/main/scala/org/hyperledger/identus/pollux/sdjwt/SDJWT.scala
pollux/sd-jwt/src/test/scala/org/hyperledger/identus/pollux/sdjwt/SDJWTSpec.scala

This change allows the Holder to make a presentation without sending the claims to be disclosed separately. As a result, the DIDComm attachment will only contain the presentation
https://input-output.atlassian.net/browse/ATL-7240

fix: Update the Holder to send the presentation only, No claims to disclose is needed separately 

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/PresentProofController.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/PresentProofControllerImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/error/PresentationError.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/repository/PresentationRepository.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/repository/PresentationRepositoryInMemory.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/MockPresentationService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceNotifier.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/repository/PresentationRepositorySpecSuite.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceSpec.scala
pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/JdbcPresentationRepository.scala

https://input-output.atlassian.net/browse/ATL-6835

fix: Present Error Handling (Part 1: Repo Changes)

---

build.sbt

- republish the @FabioPinheiro [PR](https://github.com/hyperledger/identus-cloud-agent/pull/900) with DCO to disable the docker image build for the pollux building block

build: make docker image only for the server

---

.github/workflows/auto-merge.yml

- rewrite the script that is able to automatically merge the main branch into the feature branch

ci: refactor auto-merge flow to use GitHub script and don't block the CI [skip ci]

---

tests/integration-tests/README.md

Rolled back `style="text-align: center"` to `align="center"` for readme in integration test

chore: fix image centering in integration test

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/CredentialIssuerEndpoints.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/http/CredentialErrorResponse.scala

This fix some issues when generating OAS client as it fails some validation. New client release is required for new oid4vci test scenarios.

fix: avoid name and operationId conflict when creating oas client

---

cloud-agent/service/wallet-api/src/main/scala/org/hyperledger/identus/agent/walletapi/sql/JdbcDIDNonSecretStorage.scala

During integration testing, there was a bug when using both longForm and shortForm DID together because inconsistency when lookup the table.This PR makes the lookup use `Get` `Put` typeclass instead of adhoc `.toString`.

fix: use Put and Get for DID in doobie statement

---

.sbtopts
build.sbt
project/build.properties

This PR make sure quill pick up the `quill.macro.log=false` flag. This remove a all of static query logs. However this does not make the log of `Dynamic Query Detected ...` logs disappeared. It would require a change in the [library here](https://github.com/zio/zio-protoquill/blob/49a4351751bae2cf764e7360429f611c1a159164/quill-sql/src/main/scala/io/getquill/context/StaticTranslationMacro.scala#L299).

build: make sure -Dquill.macro.log=false is passed when quill compiles

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/PresentBackgroundJobs.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/repository/PresentationRepository.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceNotifier.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/repository/PresentationRepositoryInMemory.scala
pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/JdbcCredentialRepository.scala
pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/JdbcPresentationRepository.scala

Add reportProcessingFailure back in PresentationRepository
Fix: this was removed recently in another PR 
Work for ATL-6932 and ATL-7329

fix: add reportProcessingFailure back in PresentationRepository

---

.github/workflows/auto-merge.yml

Any PR with `autoupdate` label gets the merge from `main` but the default `GITHUB_TOKEN` [will not trigger another workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow).
However, this requires `IDENTUS_CI` to have these permissions

ci: do not use default token for autoupdate CI job [skip ci]

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/PresentBackgroundJobs.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceNotifier.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/repository/PresentationRepositorySpecSuite.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/MockPresentationService.scala

PresentationRepository update updateAfterFail doesn't throw error, Chnaged IO to UIO

fix: changed IO to UIO as as underline repository doesn't throw error

---

.github/workflows/auto-merge.yml

We don't have control over `IDENTUS_CI` token permissions. Now, switching back to our own token so we can grant the right permissions. Later we will ask `IDENTUS_CI` to be updated.

ci: use IDENTUS_CI2 token for automerge [skip ci]

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/connect/controller/http/Connection.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/issue/controller/http/IssueCredentialRecord.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/PresentationStatus.scala

https://input-output.atlassian.net/browse/ATL-6933

feat: Expose Stored Error

---

build.sbt
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/ControllerHelper.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/DIDStateSyncBackgroundJobs.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/PresentBackgroundJobs.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/PresentProofController.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/PresentProofControllerImpl.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/PresentProofEndpoints.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/PresentProofServerEndpoints.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/AcceptRequestPresentationInvitation.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/OOBPresentationInvitation.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/OOBRequestPresentationInput.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/PresentationStatus.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/PresentationStatusPage.scala
mercury/protocol-invitation/src/test/scala/org/hyperledger/identus/mercury/protocol/invitation/v2/OutOfBandSpec.scala
mercury/protocol-present-proof/src/main/scala/org/hyperledger/identus/mercury/protocol/presentproof/PresentProofInvitation.scala
mercury/protocol-present-proof/src/main/scala/org/hyperledger/identus/mercury/protocol/presentproof/RequestPresentation.scala
mercury/protocol-present-proof/src/test/scala/org/hyperledger/identus/mercury/protocol/presentproof/RequestPresentationSpec.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/PresentationRecord.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/error/PresentationError.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceNotifier.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/repository/PresentationRepositorySpecSuite.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/MockPresentationService.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceNotifierSpec.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceSpec.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceSpecHelper.scala
pollux/sql-doobie/src/main/resources/sql/pollux/V24__add_invitation_column_presentation_record.sql
pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/JdbcPresentationRepository.scala

This PR introduces two new endpoints in the present-proof flow:
An endpoint to create an Out-of-Band (OOB) invitation with a Request Presentation attached in a DIDComm message. This also updates the PresentationRecord with a new state, InvitationGenerated, and stores the invitation within the PresentationRecord.(https://input-output.atlassian.net/browse/ATL-6624)
An endpoint to accept the OOB invitation, parse the OOB message, and update the protocol state to RequestReceived.
(https://input-output.atlassian.net/browse/ATL-6630)

feat: connection less presentation

---

.github/workflows/build.yml

In this PR the BUILD_VERSION is changed to be PROJECT_VERSION-BUILD-NUMBER-COMMIT_SHA.
This change is required to add the possibility for the ArgoCD to track the latest version of the build.

ci: make-revision-semver-compliant

---

.github/workflows/build.yml

This PR contains the fix to the previous one
The tag should be {VERSION}-{BUILD_NUMBER}-{COMMIT_SHA}

ci: make revision semver compliant (fix the order)

---

.github/workflows/release.yml
release.config.mjs
version.sbt

In this PR, the release configuration is fixed to set the next version of the project higher after release.
The docker build step is moved to the right location
The generation of the DEPENDENCIES.md file with contain the same release version

ci: set next version properly

---

cloud-agent/service/wallet-api/src/main/scala/org/hyperledger/identus/agent/walletapi/sql/JdbcGenericSecretStorage.scala
cloud-agent/service/wallet-api/src/main/scala/org/hyperledger/identus/agent/walletapi/sql/model/GenericSecret.scala
cloud-agent/service/wallet-api/src/main/scala/org/hyperledger/identus/agent/walletapi/sql/model/Wallet.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/MockPresentationService.scala

fix: migrate to quill for generic secret storage

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/issue/controller/IssueEndpoints.scala

fix for the issue when publishing cloud agent client
https://github.com/hyperledger/identus-cloud-agent/actions/runs/10600696602/job/29379084131

fix: operation id repeated error

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/BackgroundJobsHelper.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/service/OIDCCredentialIssuerService.scala
cloud-agent/service/server/src/test/scala/org/hyperledger/identus/verification/controller/VcVerificationControllerImplSpec.scala
cloud-agent/service/server/src/test/scala/org/hyperledger/identus/verification/controller/VcVerificationControllerTestTools.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceImpl.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/repository/CredentialStatusListRepositoryInMemory.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceSpec.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceSpecHelper.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/verification/VcVerificationServiceImplSpec.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/verification/VcVerificationServiceSpecHelper.scala
pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/JdbcCredentialStatusListRepository.scala
pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/VerifiableCredentialPayload.scala
pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/VerifiablePresentationPayload.scala
pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/revocation/VCStatusList2021.scala
pollux/vc-jwt/src/test/scala/org/hyperledger/identus/pollux/vc/jwt/JWTVerificationTest.scala
pollux/vc-jwt/src/test/scala/org/hyperledger/identus/pollux/vc/jwt/revocation/VCStatusList2021Spec.scala

https://input-output.atlassian.net/browse/ATL-7741

fix: Remove type DID

---

.scala-steward.conf

Disable the run of scalafmt in the Scala Steward PRs

ci: disable scalafmt run in the Scala Steward PRs [skip ci]

---

infrastructure/charts/agent/templates/apisixroute.yaml

It's a polishing of the helm chart configuration for the cloud-agent and APISIX in the scope of renaming from `prism-agent` to the `cloud-agent`
It's expected that this change will fix the issue in the SIT environment

fix: remove `prism-agent` path from the apisixroute.yaml

---

pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/VerifiableCredentialPayload.scala
pollux/vc-jwt/src/test/scala/org/hyperledger/identus/pollux/vc/jwt/JWTVerificationTest.scala

https://input-output.atlassian.net/browse/ATL-7661

feat: Test JWT OBJECT as Issuer

---

README.md

Update README.md to remove GITHUB_TOKEN as a prerequisite

docs: Update README.md rempve GITHUB_TOKEN prerequisite

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/controller/CredentialIssuerController.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/service/OIDCCredentialIssuerService.scala
cloud-agent/service/server/src/test/scala/org/hyperledger/identus/oid4vci/domain/OIDCCredentialIssuerServiceSpec.scala

https://input-output.atlassian.net/browse/ATL-7756

fix: cannot reuse the same credential-offer in oid4vci

---

pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/OID4VCIIssuerMetadataService.scala

ATL-7837
Return 404 response instead of 500 when create oid4vci credential-configurations for non-existing issuer.

fix: return 404 when create credConfig on non-existing issuer

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/CredentialIssuerEndpoints.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/controller/CredentialIssuerController.scala
cloud-agent/service/wallet-api/src/main/scala/org/hyperledger/identus/agent/walletapi/service/ManagedDIDServiceWithEventNotificationImpl.scala
cloud-agent/service/wallet-api/src/main/scala/org/hyperledger/identus/agent/walletapi/util/ManagedDIDTemplateValidator.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/error/CredentialSchemaError.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/schema/CredentialSchema.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/GenericUriResolverImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/OID4VCIIssuerMetadataService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/uriResolvers/DidUrlResolver.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/OID4VCIIssuerMetadataServiceSpecSuite.scala
pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/model/db/package.scala
shared/core/src/main/scala/org/hyperledger/identus/shared/http/GenericUriResolver.scala
shared/core/src/main/scala/org/hyperledger/identus/shared/models/Failure.scala

fix: oid4vci endpoints error statuses and negative input validation

---

pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/VerifiableCredentialPayload.scala
pollux/vc-jwt/src/test/scala/org/hyperledger/identus/pollux/vc/jwt/JWTVerificationTest.scala

https://input-output.atlassian.net/browse/ATL-7663

feat: VC support for Array of credential Status

---

tests/integration-tests/README.md
tests/integration-tests/src/test/kotlin/config/services/Agent.kt
tests/integration-tests/src/test/kotlin/config/services/Keycloak.kt
tests/integration-tests/src/test/kotlin/config/services/ServiceBase.kt
tests/integration-tests/src/test/kotlin/config/services/Vault.kt
tests/integration-tests/src/test/kotlin/config/services/VerifiableDataRegistry.kt
tests/integration-tests/src/test/kotlin/steps/oid4vci/IssueCredentialSteps.kt
tests/integration-tests/src/test/kotlin/steps/oid4vci/ManageCredentialConfigSteps.kt
tests/integration-tests/src/test/kotlin/steps/oid4vci/ManageIssuerSteps.kt
tests/integration-tests/src/test/resources/features/oid4vci/issue_jwt.feature
tests/integration-tests/src/test/resources/features/oid4vci/manage_credential_config.feature
tests/integration-tests/src/test/resources/features/oid4vci/manage_issuer.feature

test: add oid4vci negative scenario tests

---

tests/integration-tests/src/test/kotlin/steps/connectionless/ConnectionLessSteps.kt
tests/integration-tests/src/test/resources/features/credential/jwt/issuance.feature
tests/integration-tests/src/test/resources/features/credential/sdjwt/issuance.feature

Added the integration test for connectionless issuance

test: Add integration test for conectionless issuance

---

pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/JdbcCredentialRepository.scala

Add the missing key_id in the query for valid AnnonCreds Credentials

fix: Add key_id missing field

---

pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceImpl.scala
tests/integration-tests/src/test/kotlin/steps/connectionless/ConnectionLessSteps.kt
tests/integration-tests/src/test/resources/features/credential/jwt/present_proof.feature
tests/integration-tests/src/test/resources/features/credential/sdjwt/present_proof.feature

Integration test for connectionless verification 

test: Add test connectionless verification 

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/http/DocModels.scala

Rely on Tapir's default value for OpenAPI spec version

chore: rely on Tapir's default value for OpenAPI spec version

---

cloud-agent/service/server/src/test/scala/org/hyperledger/identus/api/util/Tapir2StaticOAS.scala

Fix generated OAS version to 3.0.3 as TS generator fails with 3.1.0

chore: fix generated OAS version to 3.0.3 as TS generator fails with 3.1.0

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/IssueBackgroundJobs.scala

Warning is generated in connection flow which is confusing it doesn't block the flow will be good address the unecessary noise
https://github.com/hyperledger/identus-cloud-agent/issues/1426

fix: Warning on Invitation generated  on Issuance

---

pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImpl.scala

mapped the claim attributes correctly in to json

fix: mapping the claims attributes to json

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/PresentBackgroundJobs.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/PresentationStatus.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/PresentationStatusPage.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/PresentationRecord.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/repository/PresentationRepository.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceImpl.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceNotifier.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/repository/PresentationRepositoryInMemory.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/repository/PresentationRepositorySpecSuite.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/MockPresentationService.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceNotifierSpec.scala
pollux/sd-jwt/src/test/scala/org/hyperledger/identus/pollux/sdjwt/ValidClaimsSpec.scala
pollux/sql-doobie/src/main/resources/sql/pollux/V30__add_sdjwt_disclosed_claims_columns.sql
pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/JdbcPresentationRepository.scala

https://github.com/hyperledger/identus-cloud-agent/issues/1430
currently api does not display disclosed claim information.  this endpoint to reveal disclosed claims for greater clarity
{{baseUrlVerifier}}/present-proof/presentations/{{VERIFIER_PRESENTATION_ID}}
This PR fixed the this issue

fix:  Add disclose claims to presentation record credential type SDJWT 

---

docs/docusaurus/credentials/oid4vci/issue.md
docs/docusaurus/sidebars.js

There were a couple of typos in the docusaurus directory that failed the build of the documentation portal.
This PR fixed the issue.

fix: documentation build

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/issue/controller/http/IssueCredentialRecord.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/PresentationStatus.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/RequestPresentationInput.scala

Update documentation for the credential offer and present proof endpoint to make it more clear when the goal and goal code applicable
https://github.com/hyperledger/identus-cloud-agent/issues/1486

docs: api spec documentation

---

.github/workflows/build.yml
.github/workflows/release-clients.yml

actions/upload-artifact and actions/download-artifact have been deprecated and need updated.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

chore: update actions

---

docs/docusaurus/schemas/credential-schema.md
tests/integration-tests/src/test/resources/containers/agent.yml

Fix broken link for https://github.com/hyperledger/identus-docs/issues/199

docs: Broken link in Credential Schema Introduction page for hyperledger/identus-docs#199

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/api/http/ErrorResponse.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/connect/controller/http/Connection.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/credentialstatus/controller/http/StatusListCredential.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/issue/controller/http/IssueCredentialRecord.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/PresentationStatus.scala
cloud-agent/service/server/src/test/scala/org/hyperledger/identus/api/util/Tapir2StaticOAS.scala

This PR fixes issue #1115: OAS is mutated from build to build because of Instant.now() and UUID.random() functions were used in the annotations.
I tried to implement the integration tests, but it's not trivial and fragile because the Tapir OAS is static and a lot of classes must be reloaded or isolated in the dedicated classloader.

fix: openAPI mutability #1115

---

README.md
docs/docusaurus/connections/connection.md
docs/docusaurus/credentialdefinition/create.md
docs/docusaurus/credentialdefinition/delete.md
docs/docusaurus/credentials/connectionless/issue.md
docs/docusaurus/credentials/didcomm/issue.md
docs/docusaurus/credentials/didcomm/present-proof.md
docs/docusaurus/credentials/oid4vci/issue.md
docs/docusaurus/dids/create.md
docs/docusaurus/dids/deactivate.md
docs/docusaurus/dids/publish.md
docs/docusaurus/dids/update.md
docs/docusaurus/index.md
docs/docusaurus/multitenancy/admin-authz-ext-iam.md
docs/docusaurus/multitenancy/tenant-migration.md
docs/docusaurus/multitenancy/tenant-onboarding-ext-iam.md
docs/docusaurus/multitenancy/tenant-onboarding-self-service.md
docs/docusaurus/multitenancy/tenant-onboarding.md
docs/docusaurus/schemas/create.md
docs/docusaurus/schemas/credential-schema.md
docs/docusaurus/schemas/delete.md
docs/docusaurus/schemas/update.md

- all links in documentation are refactored to point to from `docs` directory to `home` directory

docs: refactor links from `docs` to `home`

---

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/connect/controller/ConnectionEndpoints.scala

when making a connection request without an APIKey: . it results in a 500 error repsonse (which is default : [unexpected error](https://tapir.softwaremill.com/en/latest/tutorials/04_errors.html#unexpected-errors)) . But it logs the exception rather than return the response returned as jsonBody[ErrorResponse]. This PR fixes it with `unauthorized` FailureVariant 
ErrorResponse(401,error:AuthenticationError:InvalidCredentials ** ,Invalid Credentials,Some(ApiKey key is not provided),error:instance:01932437-c12a-4915-9c54-45afd530222e)
Link to existing ADR (Architecture Decision Record), if any. If relevant, describe other approaches explored and the selected approach. Documenting why the methods were not selected will create a knowledge base for future reference, helping prevent others from …

fix: return proper error response for unauthorized access

---

CONTRIBUTING.md

Old link below points to a 404
https://handbook.atalaprism.io/engineering/sdlc/commit-guidelines
replaced it with 
https://github.com/hyperledger-identus/identus/blob/main/CONTRIBUTING.md#commits

fix: Commit message guideline broken link fixed

---

tests/integration-tests/src/test/kotlin/common/errors/CredentialOfferError.kt
tests/integration-tests/src/test/kotlin/common/errors/JwtCredentialError.kt
tests/integration-tests/src/test/kotlin/common/errors/SchemaTemplateError.kt
tests/integration-tests/src/test/kotlin/steps/common/CommonSteps.kt
tests/integration-tests/src/test/kotlin/steps/credentials/JwtCredentialSteps.kt
tests/integration-tests/src/test/kotlin/steps/schemas/CredentialSchemasSteps.kt
tests/integration-tests/src/test/kotlin/steps/verification/VcVerificationSteps.kt
tests/integration-tests/src/test/resources/features/credential/jwt/issuance.feature

Adds negative scenario outline for jwt credential offer

test: adds negative scenario outline for jwt credential offer

---

.github/workflows/lint.yml

- deactivate the megalinter run on the pull request (it can be run on workflow_dispatch)

build: deactivate the megalinter workflow on pull_request

---

build.sbt
cloud-agent/service/api/http/cloud-agent-openapi-spec.yaml
docs/docusaurus/credentials/revocation.md
pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/revocation/VCStatusList2021.scala
pollux/vc-jwt/src/test/scala/org/hyperledger/identus/pollux/vc/jwt/JWTVerificationTest.scala

Mitigation the problem by update the outdated url
The problem is probably our https client on code that does not follow the redirect.
Having several HTTP clients made with different libraries does not help...

fix: mitigation to #1495 (update the outdated url)

---

pollux/sql-doobie/src/main/resources/sql/pollux/V27__presentation_definition_table.sql

This PR fixes a migration issue in v27 where a column named format (a reserved keyword in PostgreSQL) was not properly wrapped in double quotes. This omission caused SQL syntax errors during migration when using PostgreSQL as the database backend.
Added double quotes (") around the format column name in the migration script to ensure compatibility with PostgreSQL.
Verified the migration runs successfully in both PostgreSQL and other supported databases (e.g., SQLite, MySQL).
PostgreSQL Compatibility: Unquoted reserved keywords (like format) cause syntax errors in PostgreSQL.
Stability: Prevents migration failures in production environments using PostgreSQL.

fix(migration): quote reserved "format" column for PostgreSQL compatibility

---

shared/json/src/main/scala/org/hyperledger/identus/shared/json/Json.scala
shared/json/src/test/scala/org/hyperledger/identus/shared/json/JsonLdLoadSpec.scala

The JSON-LD document resolution (toRfd call) is optimized to use the LRUDocumentLoader. This PR fixes #1553 issue.

fix: add LRUDocumentLoader to optimize the JsonLD.toRdf call, fix #1553

---

cloud-agent/service/server/src/main/resources/logback.xml
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/LogUtils.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/notification/WebhookPublisher.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/MainApp.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/Modules.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/IssueBackgroundJobs.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/StatusListJobs.scala
cloud-agent/service/wallet-api/src/main/scala/org/hyperledger/identus/agent/walletapi/service/ManagedDIDServiceImpl.scala
cloud-agent/service/wallet-api/src/test/scala/org/hyperledger/identus/agent/walletapi/benchmark/KeyDerivation.scala
event-notification/src/test/scala/org/hyperledger/identus/messaging/kafka/InMemoryMessagingServiceSpec.scala
mercury/agent-didcommx/src/main/scala/org/hyperledger/identus/mercury/MessagingService.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/uriResolvers/DidUrlResolver.scala
shared/core/src/main/scala/org/hyperledger/identus/shared/http/GenericUriResolver.scala
shared/core/src/main/scala/org/hyperledger/identus/shared/messaging/kafka/InMemoryMessagingService.scala

- fix LOG_LEVEL environment variable in the logback.xml file
- set WARN log level in 3rd party libraries: blaze, flyway, hikari, netty
- rename ZIO.debug (writes to the stdout) to ZIO.logDebug to control the logging level
- fixed duplicates of the message about the configured URL of API and DIDComm
- simplified the salutation message

fix: LOG_LEVEL environment variable and cleanup logging entries

---

.github/workflows/update-oas.yml
tests/integration-tests/build.gradle.kts
tests/performance-tests/agent-performance-tests-k6/.yarnrc
tests/performance-tests/agent-performance-tests-k6/README.md
tests/performance-tests/agent-performance-tests-k6/package.json
tests/performance-tests/agent-performance-tests-k6/run.sh
tests/performance-tests/agent-performance-tests-k6/src/actors/Actor.ts
tests/performance-tests/agent-performance-tests-k6/src/actors/Holder.ts
tests/performance-tests/agent-performance-tests-k6/src/actors/Issuer.ts
tests/performance-tests/agent-performance-tests-k6/src/actors/Verifier.ts
tests/performance-tests/agent-performance-tests-k6/src/actors/index.ts
tests/performance-tests/agent-performance-tests-k6/src/common/ConnectionService.ts
tests/performance-tests/agent-performance-tests-k6/src/common/CredentialsService.ts
tests/performance-tests/agent-performance-tests-k6/src/common/DidService.ts
tests/performance-tests/agent-performance-tests-k6/src/common/HttpService.ts
tests/performance-tests/agent-performance-tests-k6/src/common/ProofsService.ts
tests/performance-tests/agent-performance-tests-k6/src/tests/common.ts
tests/performance-tests/agent-performance-tests-k6/src/tests/credentials/credential-definition-test.ts
tests/performance-tests/agent-performance-tests-k6/src/tests/credentials/credential-offer-test.ts
tests/performance-tests/agent-performance-tests-k6/src/tests/credentials/credential-schema-test.ts
tests/performance-tests/agent-performance-tests-k6/src/tests/dids/create-prism-did-test.ts
tests/performance-tests/agent-performance-tests-k6/src/tests/dids/did-publishing-test.ts
tests/performance-tests/agent-performance-tests-k6/src/tests/flows/connection-flow-test.ts
tests/performance-tests/agent-performance-tests-k6/src/tests/flows/issuance-flow-test.ts
tests/performance-tests/agent-performance-tests-k6/src/tests/flows/present-proof-flow-test.ts
tests/performance-tests/agent-performance-tests-k6/webpack.config.js
tests/performance-tests/agent-performance-tests-k6/yarn.lock

- update the identus-cloud-agent-client dependency in the performance tests module
- run the megalinter to adjust the TypeScript files
- upgrade the dependency of the cloud-agent-client in the e2e test and switch to Sonatype Central repo

refactor: update http client dependencies

---

cloud-agent/client/generator/publish-clients.sh
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/castor/controller/DIDRegistrarEndpoints.scala
release.config.mjs

Synthetic commit to trigger the major version release of the cloud-agent in the semantic-release workflow.

chore!: trigger major version release

---

.scalafmt.conf
build.sbt
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/config/AppConfig.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/PresentBackgroundJobs.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/issue/controller/IssueControllerImpl.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/CredentialIssuerServerEndpoints.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/PresentProofControllerImpl.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/PresentationStatus.scala
cloud-agent/service/wallet-api/src/main/scala/org/hyperledger/identus/agent/walletapi/sql/JdbcDIDNonSecretStorage.scala
connect/core/src/test/scala/org/hyperledger/identus/connect/core/repository/ConnectionRepositorySpecSuite.scala
connect/core/src/test/scala/org/hyperledger/identus/connect/core/service/ConnectionServiceImplSpec.scala
mercury/agent-didcommx/src/main/scala/org/hyperledger/identus/mercury/model/Conversions.scala
mercury/protocol-issue-credential/src/main/scala/org/hyperledger/identus/mercury/protocol/issuecredential/Utils.scala
pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceNotifier.scala
pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImplSpec.scala
pollux/vc-jwt/src/test/scala/org/hyperledger/identus/pollux/vc/jwt/JwtPresentationTest.scala
project/build.properties
project/plugins.sbt

Fix typo `scijava` in build file causing flaky `scalafmt` tasks.
For example: https://github.com/hyperledger-identus/cloud-agent/actions/runs/14996376621/job/42131525428
Debugged stack trace of a failed attempt
Also ran `scalafix`  and upgrade fix / fmt plugins.

build: fix typo in repository causing flaky scalafmt

---

build.sbt
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/Modules.scala
cloud-agent/service/vdr/src/main/scala/org/hyperledger/identus/agent/vdr/VdrService.scala

Update VDR HTTP binding on the agent to use `vdr://` URL scheme

fix: use custom vdr scheme for vdr endpoints

---

build.sbt
cloud-agent/service/server/src/main/resources/application.conf
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/api/http/EndpointOutputs.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/castor/controller/DIDRegistrarEndpoints.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/event/controller/EventEndpoints.scala
cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/CredentialIssuerEndpoints.scala
tests/integration-tests/src/test/resources/containers/agent.yml

- https://github.com/hyperledger-identus/cloud-agent/issues/1621
- https://github.com/hyperledger-identus/cloud-agent/issues/1627
`commons-logging` is added to fix issue when enabling keycloak.

fix: update default value for API_KEY_AUTO_PROVISIONING to false
