pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/CredentialDefinitionServiceImpl.scala, prism-agent/service/server/src/test/scala/io/iohk/atala/pollux/credentialdefinition/CredentialDefinitionBasicSpec.scala, prism-agent/service/wallet-api/src/main/scala/io/iohk/atala/agent/walletapi/vault/VaultDIDSecretStorage.scala
https://input-output.atlassian.net/browse/ATL-5642
=> fix: correct vault path

mercury/mercury-library/models/src/main/scala/io/iohk/atala/mercury/model/AttachmentDescriptor.scala, mercury/mercury-library/protocol-issue-credential/src/main/scala/io/iohk/atala/mercury/protocol/issuecredential/Credential.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/CredentialService.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/issue/controller/IssueController.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/issue/controller/http/IssueCredentialRecord.scala
fix: CredentialOffer not following spec
Fixes ATL-4146
=> fix: CredentialOffer not following spec

README.md
Removes handbook link from readme
Update the compatibility table for agent v1.12.0
=> docs: remove internal handbook link from readme [skip ci]

infrastructure/charts/agent/templates/apisixroute.yaml
Fixes ATL-xxxx
Fixes: Fixing identation in apisixroute
=> fix: indentation in apisixroute

infrastructure/charts/agent/templates/apisixroute.yaml
Fixes ATL-xxxx
fix: Fixing identation in apisixroute 2.
=> fix: another indentation in apisixroute

infrastructure/charts/agent/templates/apisixroute.yaml
This fixes the APISIX configuration not passing validation due to concatenated route name being too long (max length is `100`). Config route and rule names where shortened to solve this.
From the APISIX logs:
```
2023-09-06T18:08:48+08:00 [33mwarn[0m apisix/apisix_route.go:513  sync ApisixRoute failed, will retry {"object": {"Type":2,"Object":{"Key":"sit-prism-agent-holder/agent-credential-definition-registry-route","OldObject":{},"GroupVersion":"apisix.apache.org/v2"},"OldObject":null,"Tombstone":null}, "error": "1 error occurred:\n\t* unexpected status code 400; error message: {\"error_msg\":\"invalid configuration: property \\\"name\\\" validation failed: string too long, expected at most 100, got 107\"}\n\n\n"}
2023-09-06T18:08:48+08:00 [33mwarn[0m apisix/route.go:74  route not …
```
=> fix: APISIX config route and rule names too long

infrastructure/charts/agent/templates/apisixroute.yaml
=> fix: add missing leading '/' in rewrite rule target

.github/workflows/performance-tests.yml
Fixes performance tests after multitenancy update
=> test: add multitenancy settings for performance tests

infrastructure/charts/agent/templates/_helpers.tpl, infrastructure/charts/agent/templates/apisixroute.yaml
Configures APISIX routing and rewrite-response plugin to set effective security headers as well as a traceable request ID
Completes ATL-5409
=> feat: add security headers in helm-chart apisix route

README.md
Simplify compatibility table to remove the requirement to update it each time new cloud agent is released
=> docs: simplify compatibility table [skip ci]

docs/docusaurus/multitenancy/tenant-onboarding.md, infrastructure/shared/docker-compose.yml
=> docs: address multi-tenant docs review feedback

docs/capabilities/multi-tenancy.md
Engineering documentation of the MT feature
Fixes ATL-4091
=> docs: engineering documentation of the multi-tenancy feature [skip CI]

README.md
Updates docs with the latest release of cloud agent
=> docs: update readme with latest release 1.12.0

.github/workflows/performance-tests.yml
=> ci: specify scope for perofmance tests auth

.gitmodules, infrastructure/charts/agent/templates/deployment.yaml, infrastructure/charts/agent/templates/postgresql.yaml
Enables support for *-application-users with multi-tenancy
=> fix: use postgres application user

prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/PrismAgentApp.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/config/AppConfig.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/iam/authentication/admin/AdminApiKeyAuthenticatorImpl.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/iam/entity/http/model/CreateEntityRequest.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/iam/entity/http/model/UpdateEntityNameRequest.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/iam/wallet/http/WalletManagementEndpoints.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/iam/wallet/http/controller/WalletManagementController.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/iam/wallet/http/model/CreateWalletRequest.scala, prism-agent/service/wallet-api/src/main/resources/sql/agent/V11__wallet_seed_digest.sql, prism-agent/service/wallet-api/src/main/scala/io/iohk/atala/agent/walletapi/model/KeyManagement.scala, prism-agent/service/wallet-api/src/main/scala/io/iohk/atala/agent/walletapi/service/WalletManagementService.scala, prism-agent/service/wallet-api/src/main/scala/io/iohk/atala/agent/walletapi/service/WalletManagementServiceImpl.scala, prism-agent/service/wallet-api/src/main/scala/io/iohk/atala/agent/walletapi/sql/JdbcWalletNonSecretStorage.scala, prism-agent/service/wallet-api/src/main/scala/io/iohk/atala/agent/walletapi/storage/WalletNonSecretStorage.scala, prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/service/WalletManagementServiceSpec.scala, prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/storage/JdbcEntityRepositorySpec.scala, prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/storage/JdbcWalletNonSecretStorageSpec.scala, prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/storage/StorageSpecHelper.scala, prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/storage/WalletSecretStorageSpec.scala
- ATL-5759: add wallet name and entity name OAS validation
- ATL-5760: fix verbosity of log message and creating a wallet / entity
- ATL-5761: reject wallet creation when seed is not unique
- ATL-5764: reject wallet creation when id is not unique
- and some other minor fixes
=> fix(prism-agent): refine multi-tenant error response and validations

infrastructure/charts/agent/templates/postgresql.yaml
=> fix: change attribute for appuser to login

infrastructure/charts/agent/templates/_helpers.tpl
Simple fix - changing a header param that was misspelled 
Relates to ATL-5409
This PR supersedes #710 and is recreated to ensure DCO sign off is correct
=> fix: correct typo on sts header (dmax -> max)

package.json
fix: Renaming values.yml [skip ci] ATL-5777 
Fixes ATL-5777
=> fix: Renaming values.yml [skip ci] ATL-5777 

package.json
=> fix: Changing yq command [skip ci] ATL-5777

infrastructure/argocd-state/d-useast1-sjd4e/values.yaml, infrastructure/argocd-state/i-eucentral1-prt9a/values.yaml
=> fix: Adding labels [skip ci]

pollux/lib/anoncredsTest/src/test/scala/Uniffy.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/secret/CredentialDefinitionSecret.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/CredentialDefinitionServiceImpl.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/CredentialServiceImpl.scala, prism-agent/service/server/src/test/scala/io/iohk/atala/issue/controller/IssueControllerTestTools.scala, prism-agent/service/server/src/test/scala/io/iohk/atala/pollux/credentialdefinition/CredentialDefinitionBasicSpec.scala, prism-agent/service/wallet-api/src/main/scala/io/iohk/atala/agent/walletapi/storage/GenericSecretStorage.scala, prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/storage/GenericSecretStorageSpec.scala
This is a tech debt refactoring needed for link secret storage
=> fix: generified generic secret storage

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/IssueCredentialRecord.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/error/CredentialServiceError.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/error/LinkSecretError.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/CredentialServiceImpl.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/CredentialServiceNotifier.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/LinkSecretService.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/LinkSecretServiceImpl.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/MockCredentialService.scala, pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/CredentialServiceSpecHelper.scala, pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/LinkSecretServiceImplSpec.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/Main.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/issue/controller/IssueController.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/issue/controller/IssueControllerImpl.scala, prism-agent/service/server/src/test/scala/io/iohk/atala/issue/controller/IssueControllerTestTools.scala
Fixes https://input-output.atlassian.net/browse/ATL-5827
=> feat: store link secret

prism-agent/client/kotlin/build.gradle, prism-agent/client/python/setup.py, prism-agent/client/typescript/package.json
Fixes repository and names for open enterprise agent rest API clients.
=> fix: change repository and name for rest api clients

infrastructure/shared/apisix/conf/apisix.yaml
=> fix(prism-agent): configure APISIX to return CORS headers from Prism Agent endpoints

infrastructure/shared/docker-compose.yml
=> fix(prism-agent): fix docker env variables interpolation issue

.github/workflows/release-clients.yml
Fixes a repository for npm agent client publishing
=> chore: fix npm client publishing repo

infrastructure/charts/agent/templates/deployment.yaml, infrastructure/charts/agent/templates/stringsecret-agent-admin-token.yaml, infrastructure/charts/agent/templates/stringsecret-agent-api-key-salt.yaml, infrastructure/charts/agent/templates/stringsecret-agent-wallet-seed.yaml
=> feat: add new auth params

docs/docusaurus/credentials/issue.md
Fixes [ATL-5875](https://input-output.atlassian.net/browse/ATL-5875)
=> docs: fix typo in docs link

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/PresentationServiceImpl.scala
Fixes https://input-output.atlassian.net/browse/ATL-5966
=> feat:  presentation API refactor

.github/workflows/release-clients.yml, pollux/lib/sql-doobie/src/main/scala/io/iohk/atala/pollux/sql/model/db/VerificationPolicy.scala, pollux/lib/sql-doobie/src/test/scala/io/iohk/atala/pollux/sql/VerificationPolicySqlIntegrationSpec.scala, prism-agent/client/generator/generate-clients.sh
=> ci: fix client generation

package.json
Automatically update .env file with the most recently released version of agent
=> chore: update .env file with each release

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/error/PresentationError.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/PresentationServiceImpl.scala, pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/PresentationServiceSpec.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/presentproof/controller/PresentProofController.scala
Fixes https://input-output.atlassian.net/browse/ATL-5967
=> feat: Receive/Store Presentation Request

castor/lib/core/src/main/scala/io/iohk/atala/castor/core/service/DIDService.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/issue/controller/IssueControllerImpl.scala
=> fix(prism-agent): more descriptive error response for validateDID in issue flow

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/IssueCredentialRecord.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/error/PresentationError.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/repository/CredentialRepositoryInMemory.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/PresentationServiceImpl.scala, pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/repository/CredentialRepositorySpecSuite.scala, pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/PresentationServiceNotifierSpec.scala, pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/PresentationServiceSpec.scala, pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/PresentationServiceSpecHelper.scala, pollux/lib/sql-doobie/src/main/scala/io/iohk/atala/pollux/sql/repository/JdbcCredentialRepository.scala
=> feat: Accept Presentation Request

prism-agent/service/server/src/test/scala/io/iohk/atala/iam/authorization/core/EntityPermissionManagementSpec.scala, prism-agent/service/server/src/test/scala/io/iohk/atala/iam/authorization/keycloak/admin/KeycloakPermissionManagementServiceSpec.scala, prism-agent/service/wallet-api/src/test/scala/io/iohk/atala/agent/walletapi/service/WalletManagementServiceSpec.scala
Fixes ATL-6082. Add unit tests for self-service wallet management.
=> test: add wallet uma permission management tests

tests/integration-tests/src/test/kotlin/common/TestConstants.kt, tests/integration-tests/src/test/kotlin/features/Init.kt, tests/integration-tests/src/test/resources/configs/two_agents_basic.conf
Fixes initialization of integration tests to unblock correct runs of multi-agent configs.
=> test: fix multi-agent config support

infrastructure/charts/agent/templates/deployment.yaml, infrastructure/charts/agent/values.yaml
=> feat: env vars support through values file

prism-agent/service/server/src/main/scala/io/iohk/atala/issue/controller/http/IssueCredentialRecord.scala
=> fix: correct OAS example

infrastructure/charts/agent/templates/deployment.yaml
Adding Liveness, and readiness probes
Fixes ATL-xxxx
=> feat: Liveness, and readiness probes

infrastructure/charts/agent/templates/deployment.yaml, infrastructure/charts/agent/values.yaml
=> fix: Swithing to startupProbe from Readiness

infrastructure/charts/agent/templates/postgresql.yaml, infrastructure/charts/agent/values.yaml
=> feat: Tune postgresql - helm chart

infrastructure/charts/agent/templates/postgresql.yaml
=> chore: quoute for postgresql definition - helm chart

infrastructure/charts/agent/templates/postgresql.yaml, infrastructure/charts/agent/values.yaml
=> fix: Change resource defaults for postgres

docs/decisions/20240103-use-jwt-claims-for-agent-admin-auth.md
=> docs: add ADR on supporting admin auth using keycloak JWT

prism-agent/service/server/src/main/scala/io/iohk/atala/pollux/credentialschema/SchemaRegistryEndpoints.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/pollux/credentialschema/SchemaRegistryServerEndpoints.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/pollux/credentialschema/controller/CredentialSchemaController.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/pollux/credentialschema/controller/CredentialSchemaControllerImpl.scala, prism-agent/service/server/src/test/scala/io/iohk/atala/pollux/schema/CredentialSchemaBasicSpec.scala, prism-agent/service/server/src/test/scala/io/iohk/atala/pollux/schema/CredentialSchemaTestTools.scala
https://input-output.atlassian.net/browse/ATL-6320
=> feat: interoperable schema api

prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/http/DocModels.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/castor/controller/DIDRegistrarEndpoints.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/castor/controller/http/ManagedDID.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/castor/controller/http/Service.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/castor/controller/http/UpdateManagedDID.scala
=> docs(prism-agent): improve did-registrar OpenAPI doc

tests/integration-tests/README.md, tests/integration-tests/src/test/kotlin/config/AgentRole.kt, tests/integration-tests/src/test/kotlin/config/Role.kt, tests/integration-tests/src/test/kotlin/config/services/Keycloak.kt, tests/integration-tests/src/test/kotlin/config/services/ServiceBase.kt, tests/integration-tests/src/test/kotlin/features/Init.kt, tests/integration-tests/src/test/resources/configs/mt_keycloak_agent_role.conf
Fixes ATL-6074. Add test configuration where `Admin` and `Tenant` has role assigned in the  JWT.
=> test: add integration test configuration for keycloak JWT with role

prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/http/DocModels.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/castor/controller/DIDEndpoints.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/castor/controller/http/DIDDocument.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/castor/controller/http/DIDResolutionResult.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/castor/controller/http/ManagedDID.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/iam/wallet/http/WalletManagementEndpoints.scala
=> docs: improve oas doc for DID and wallet endpoints

README.md
=> docs(prism-agent): update readme file to the latest Agent version, fix the broken link to the container registry

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/PresentationServiceImpl.scala, pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/repository/PresentationRepositorySpecSuite.scala
Fixes https://input-output.atlassian.net/browse/ATL-6489
=> feat: Refactor Anoncred Duplicate Code

.github/labeler.yml, .github/workflows/labeler.yml, .github/workflows/lint.yml, .github/workflows/pr-lint.yml, .github/workflows/unit-tests.yml
Upgrade any GH action plugin that fail the workflow due to `node20` upgrade.
=> ci: upgrade action plugin versions

.github/labeler.yml, build.sbt, mercury/mercury-library/agent-didcommx/src/main/scala/io/iohk/atala/mercury/AgentPeerService.scala, mercury/mercury-library/agent-didcommx/src/main/scala/io/iohk/atala/mercury/PeerDID.scala, mercury/mercury-library/resolver/src/main/scala/io/iohk/atala/resolvers/PeerDidResolver.scala, mercury/mercury-library/resolver/src/test/scala/io/iohk/atala/resolvers/PeerDidResolverSpec.scala
BREAKING CHANGE
Update to support latest peer did spec
The PeerDID JVM  new spec  https://identity.foundation/peer-did-method-spec
=> fix(prism-agent):  update didcomm peerdid library to support latest spec

prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/http/DocModels.scala
=> docs(prism-agent): fix agent OAS spec issues and add contacts infos

prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/http/DocModels.scala
=> docs(prism-agent): remove the contact section from the OAS spec

.github/workflows/performance-tests.yml, infrastructure/single-tenant-testing-stack/run-performance-tests-local.sh, tests/performance-tests/atala-performance-tests-k6/README.md, tests/performance-tests/atala-performance-tests-k6/src/actors/Issuer.ts, tests/performance-tests/atala-performance-tests-k6/src/common/Config.ts, tests/performance-tests/atala-performance-tests-k6/src/common/CredentialsService.ts, tests/performance-tests/atala-performance-tests-k6/src/scenarios/default.ts, tests/performance-tests/atala-performance-tests-k6/src/tests/credentials/credential-definition-test.ts
Adds a test to check the performance of creating a credential definition for AnonCreds credentials
=> feat: add credential def performance test

prism-agent/service/server/src/main/resources/application.conf, prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/Modules.scala
=> fix: correct the config environment variable name

docs/docusaurus/credentials/present-proof.md, prism-agent/service/server/src/main/scala/io/iohk/atala/presentproof/controller/http/RequestPresentationAction.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/presentproof/controller/http/RequestPresentationInput.scala
Fixes https://input-output.atlassian.net/browse/ATL-6026
=> feat: Update documentation

docs/capabilities/multi-tenancy.md
Fixed environment variable name to enable default entity and wallet.
=> docs: update multi-tenancy.md

prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/config/AppConfig.scala, prism-agent/service/server/src/test/scala/io/iohk/atala/agent/server/config/AppConfigSpec.scala
https://github.com/hyperledger-labs/open-enterprise-agent/issues/859 
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
=> fix(prism-agent): add validation for endpoint url

.mega-linter.yml
https://input-output.atlassian.net/browse/ATL-6027
=> fix: add Anoncreds Integration Test

docs/docusaurus/secrets/operation.md
- [] My PR follows the [contribution guidelines](https://github.com/hyperledger-labs/open-enterprise-agent/blob/main/CONTRIBUTING.md) of this project
- [] My PR is free of third-party dependencies that don't comply with the [Allowlist](https://toc.hyperledger.org/governing-documents/all …
=> docs: add missing vault env from docs

tests/integration-tests/src/test/kotlin/steps/credentials/IssueCredentialsSteps.kt, tests/integration-tests/src/test/kotlin/steps/proofs/AnoncredsPresentProofSteps.kt, tests/integration-tests/src/test/resources/features/proofs/present_proof_anoncred.feature
https://input-output.atlassian.net/browse/ATL-6027
=> fix: anoncred test

.github/workflows/deployment.yml
=> ci: upgrade deployment action to v3 (node 20)

.github/workflows/integration-tests.yml, .github/workflows/release-clients.yml, tests/integration-tests/build.gradle.kts, tests/integration-tests/src/test/kotlin/steps/schemas/CredentialSchemasSteps.kt, tests/integration-tests/src/test/kotlin/steps/verificationpolicies/VerificationPoliciesSteps.kt
- Fixes slack notification due missing json summary file
- Adds parameter on workflow_dispatch for agent client publication
=> test: integration slack notification fix + parameter on client publication

package.json
The signer is changed from Anton to Allain
=> ci: update the release commit message

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/verification/VcVerificationService.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/verification/VcVerificationServiceImpl.scala, pollux/lib/vc-jwt/src/main/scala/io/iohk/atala/pollux/vc/jwt/VerifiableCredentialPayload.scala
https://input-output.atlassian.net/browse/ATL-6788
https://input-output.atlassian.net/browse/ATL-6780
https://input-output.atlassian.net/browse/ATL-6774
https://input-output.atlassian.net/browse/ATL-6781
=> feat: Signature, Not Before, Expiration, Schema Verification API

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/model/schema/CredentialSchema.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/CredentialServiceImpl.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/verification/VcVerificationService.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/verification/VcVerificationServiceImpl.scala, pollux/lib/vc-jwt/src/main/scala/io/iohk/atala/pollux/vc/jwt/JWTVerification.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/agent/server/PrismAgentApp.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/VcVerificationControllerImpl.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/ParameterizableVcVerification.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerification.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerificationParameter.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerificationRequest.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerificationResponse.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerificationResult.scala
https://input-output.atlassian.net/browse/ATL-6785
https://input-output.atlassian.net/browse/ATL-6789
=> feat: Semantic-Subject-Verification

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, SECURITY.md, docs/decisions/20240116-use-zio-failures-and-defects-effectively.md, infrastructure/charts/index.yaml
from:
https://github.com/hyperledger-labs/open-enterprise-agent
https://raw.githubusercontent.com/hyperledger-labs/open-enterprise-agent
to:
https://github.com/hyperledger/identus-cloud-agent
https://raw.githubusercontent.com/hyperledger/identus-cloud-agent
=> chore: update references to identus

pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/verification/VcVerification.scala, pollux/lib/core/src/main/scala/io/iohk/atala/pollux/core/service/verification/VcVerificationServiceImpl.scala, pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/verification/VcVerificationServiceImplSpec.scala, pollux/lib/core/src/test/scala/io/iohk/atala/pollux/core/service/verification/VcVerificationServiceSpecHelper.scala, pollux/lib/vc-jwt/src/main/scala/io/iohk/atala/pollux/vc/jwt/VerifiableCredentialPayload.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/VcVerificationControllerImpl.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/VcVerificationEndpoints.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/VcVerificationServerEndpoints.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerification.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/verification/controller/http/VcVerificationParameter.scala, prism-agent/service/server/src/test/scala/io/iohk/atala/verification/controller/VcVerificationControllerImplSpec.scala, prism-agent/service/server/src/test/scala/io/iohk/atala/verification/controller/VcVerificationControllerTestTools.scala
https://input-output.atlassian.net/browse/ATL-6777
=> feat: VC Verification test coverage

connect/lib/core/src/main/scala/io/iohk/atala/connect/core/service/MockConnectionService.scala, prism-agent/service/server/src/main/scala/io/iohk/atala/issue/controller/IssueControllerImpl.scala, prism-agent/service/server/src/test/scala/io/iohk/atala/issue/controller/IssueControllerImplSpec.scala, prism-agent/service/server/src/test/scala/io/iohk/atala/issue/controller/IssueControllerTestTools.scala
https://github.com/hyperledger/identus/issues/956
Add checks to validate key purpose for the did
=> fix: Check purpose of the keys

.github/workflows/release.yml
=> ci: add permission to push the tag for semantic-release [skip ci]

.github/workflows/release.yml
=> ci: use hyperledger-bot instead of atala-dev account [skip ci]

.github/workflows/release.yml
=> ci: fix semantic-release

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/verification/controller/VcVerificationEndpoints.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/verification/controller/http/VcVerificationRequest.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/verification/controller/http/VcVerificationResponse.scala, cloud-agent/service/server/src/test/scala/org/hyperledger/identus/verification/controller/VcVerificationControllerImplSpec.scala, tests/integration-tests/src/test/kotlin/common/CredentialSchema.kt, tests/integration-tests/src/test/kotlin/common/TestConstants.kt, tests/integration-tests/src/test/kotlin/config/VaultAuthType.kt, tests/integration-tests/src/test/kotlin/config/services/ServiceBase.kt, tests/integration-tests/src/test/kotlin/config/services/Vault.kt, tests/integration-tests/src/test/kotlin/steps/Setup.kt, tests/integration-tests/src/test/kotlin/steps/common/CommonSteps.kt, tests/integration-tests/src/test/kotlin/steps/credentials/IssueCredentialsSteps.kt, tests/integration-tests/src/test/kotlin/steps/did/PublishDidSteps.kt, tests/integration-tests/src/test/kotlin/steps/proofs/AnoncredsPresentProofSteps.kt, tests/integration-tests/src/test/kotlin/steps/schemas/CredentialSchemasSteps.kt, tests/integration-tests/src/test/kotlin/steps/verification/VcVerificationSteps.kt, tests/integration-tests/src/test/kotlin/steps/verificationpolicies/VerificationPoliciesSteps.kt
https://input-output.atlassian.net/browse/ATL-6775
https://input-output.atlassian.net/browse/ATL-6778
=> feat(agent): verification API integration test + documentation ATL-6775

.github/workflows/release.yml
=> ci: fix release workflow to use the Hyperledger infrastructure

.github/workflows/release.yml, package.json
=> ci: fix the typo in the release step

.github/workflows/release-clients.yml, cloud-agent/client/kotlin/settings.gradle, cloud-agent/client/python/setup.py, cloud-agent/client/typescript/package.json, tests/integration-tests/build.gradle.kts
=> ci: fix release-clients.yml

.git-blame-ignore-revs, .github/.scala-steward.conf, .github/workflows/scala-steward.yml, .scala-steward.conf, .scalafmt.conf, build.sbt, cloud-agent/service/server/src/test/scala/org/hyperledger/identus/iam/authorization/keycloak/admin/KeycloakPermissionManagementServiceSpec.scala, mercury/protocol-coordinate-mediation/src/main/scala/org/hyperledger/identus/mercury/protocol/coordinatemediation/CoordinateMediation.scala, mercury/protocol-issue-credential/src/main/scala/org/hyperledger/identus/mercury/protocol/issuecredential/CredentialPreview.scala, pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/JdbcCredentialRepository.scala, project/LicenseReport.scala, project/build.properties, project/build.sbt, shared/core/src/main/scala/org/hyperledger/identus/shared/db/TransactorLayer.scala, tests/integration-tests/src/test/resources/containers/keycloak.yml
Fix scala-steward after moving repo to hyperledger
Also merge PR https://github.com/hyperledger/identus-cloud-agent/pull/867
=> ci: fix scala-steward after moving repo to hyperledger

.github/workflows/lint.yml
=> ci: fix megalinter PR creation

.github/CODEOWNERS, .github/labeler.yml, .github/workflows/lint.yml, cloud-agent/service/README.md, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/CloudAgentApp.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/MainApp.scala, cloud-agent/service/server/src/test/scala/org/hyperledger/identus/agent/server/config/AppConfigSpec.scala, docs/decisions/20230926-use-keycloak-authorisation-service-for-managing-wallet-permissions.md, docs/docusaurus/connections/connection.md, docs/docusaurus/credentialdefinition/create.md, docs/docusaurus/multitenancy/tenant-migration.md, docs/docusaurus/multitenancy/tenant-onboarding-ext-iam.md, docs/docusaurus/multitenancy/tenant-onboarding-self-service.md, docs/docusaurus/multitenancy/tenant-onboarding.md, docs/general/key-derivation-benchmark.md
Clean up 'prism` term in the project and docs
Fix the codeowners file
Fix the labeler
=> docs: cleanup other prism term entries

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/http/DocModels.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/event/controller/EventEndpoints.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/event/controller/http/CreateWebhookNotification.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/iam/entity/http/EntityEndpoints.scala
=> docs: improve OAS docs for Event and IAM section

.github/workflows/integration-tests.yml, .github/workflows/scala-steward.yml
- Fix Scala Steward DCO commit signature
=> ci: fix scala steward DCO signature

.github/workflows/integration-tests.yml, .github/workflows/lint.yml, .github/workflows/performance-tests.yml, .github/workflows/unit-tests.yml, docs/docusaurus/dids/create.md, docs/docusaurus/dids/update.md
=> docs: update new key types in DID tutorials [skip ci]

docs/decisions/20240520-use-did-urls-to-reference-resources.md
This PR adds an ADR describing how to store resources for VC verification
=> docs: Add ADR for resources storage

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/verification/controller/VcVerificationEndpoints.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/verification/controller/http/ParameterizableVcVerification.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/verification/controller/http/VcVerification.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/verification/controller/http/VcVerificationParameter.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/verification/controller/http/VcVerificationRequest.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/verification/controller/http/VcVerificationResponse.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/verification/controller/http/VcVerificationResult.scala
https://input-output.atlassian.net/browse/ATL-7158
=> fix: VC Verification API Doc

cloud-agent/service/server/src/test/scala/org/hyperledger/identus/verification/controller/VcVerificationControllerImplSpec.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/verification/VcVerificationServiceImpl.scala
https://input-output.atlassian.net/browse/ATL-7176
=> fix:  SemanticCheckOfClaims In Verification API

build.sbt, cloud-agent/service/server/src/main/resources/application.conf, cloud-agent/service/server/src/main/resources/logback.xml
=> fix:  update the jose dependency and switch back to the official library

infrastructure/charts/agent/templates/_helpers.tpl, infrastructure/charts/agent/templates/apisixroute.yaml, infrastructure/charts/agent/templates/apisixtls.yaml, infrastructure/charts/agent/templates/certificate.yaml, infrastructure/charts/agent/templates/configmap.yaml, infrastructure/charts/agent/templates/deployment.yaml, infrastructure/charts/agent/templates/postgresql.yaml, infrastructure/charts/agent/templates/service.yaml, infrastructure/charts/agent/values.yaml
=> fix: Changing .chart.name reference, adding name override

infrastructure/charts/agent/templates/_helpers.tpl
=> fix: Chart refactor

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialdefinition/controller/CredentialDefinitionController.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialdefinition/controller/CredentialDefinitionControllerImpl.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialschema/controller/CredentialSchemaController.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialschema/controller/CredentialSchemaControllerImpl.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialDefinitionService.scala
https://input-output.atlassian.net/browse/ATL-7219
=> fix: Credential Defintion Error Handling Part 2

infrastructure/charts/agent/templates/_helpers.tpl, infrastructure/charts/agent/templates/apisixconsumer.yaml, infrastructure/charts/agent/templates/apisixroute.yaml, infrastructure/charts/agent/templates/apisixtls.yaml, infrastructure/charts/agent/templates/certificate.yaml, infrastructure/charts/agent/templates/configmap.yaml, infrastructure/charts/agent/templates/deployment.yaml, infrastructure/charts/agent/templates/externalsecret.yaml, infrastructure/charts/agent/templates/postgresql.yaml, infrastructure/charts/agent/templates/service.yaml, infrastructure/charts/agent/templates/stringsecret-agent-admin-token.yaml, infrastructure/charts/agent/templates/stringsecret-agent-api-key-salt.yaml, infrastructure/charts/agent/templates/stringsecret-agent-keycloak-secret.yaml, infrastructure/charts/agent/templates/stringsecret-agent-wallet-seed.yaml, infrastructure/charts/agent/templates/stringsecret.yaml, infrastructure/charts/agent/templates/vault-unseal.yaml
=> fix: Helm chart refactor

infrastructure/charts/agent/templates/apisixroute.yaml, infrastructure/charts/agent/templates/apisixtls.yaml, infrastructure/charts/agent/templates/certificate.yaml, infrastructure/charts/agent/templates/configmap.yaml, infrastructure/charts/agent/templates/deployment.yaml, infrastructure/charts/agent/templates/postgresql.yaml, infrastructure/charts/agent/templates/service.yaml
=> fix: Helm chart refactor vol2

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/controller/CredentialIssuerController.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/domain/IssuanceSession.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/domain/Openid4VCIProofJwtOps.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/service/OIDCCredentialIssuerService.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/storage/IssuanceSessionStorage.scala, cloud-agent/service/server/src/test/scala/org/hyperledger/identus/oid4vci/domain/OIDCCredentialIssuerServiceSpec.scala, pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/VerifiableCredentialPayload.scala
=> feat: add claims to the VC

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/PresentBackgroundJobs.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/PresentProofController.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/PresentProofControllerImpl.scala, cloud-agent/service/server/src/test/scala/org/hyperledger/identus/pollux/schema/CredentialSchemaMultiTenancySpec.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/error/CredentialDefinitionServiceError.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/error/CredentialSchemaServiceError.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/model/error/PresentationError.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialDefinitionService.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialDefinitionServiceImpl.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialSchemaService.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialSchemaServiceImpl.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImpl.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/MockPresentationService.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationService.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceImpl.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceNotifier.scala
https://input-output.atlassian.net/browse/ATL-5775
=> fix: present error handling Part 2

castor/src/main/scala/org/hyperledger/identus/castor/core/service/DIDService.scala, castor/src/main/scala/org/hyperledger/identus/castor/core/util/DIDOperationValidator.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/controller/DIDRegistrarController.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/controller/DIDRegistrarServerEndpoints.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/didcomm/controller/DIDCommController.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/didcomm/controller/DIDCommControllerImpl.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/didcomm/controller/DIDCommServerEndpoints.scala, cloud-agent/service/wallet-api/src/main/scala/org/hyperledger/identus/agent/walletapi/service/ManagedDIDServiceWithEventNotificationImpl.scala, mercury/protocol-issue-credential/src/main/scala/org/hyperledger/identus/mercury/protocol/issuecredential/IssueCredential.scala, mercury/protocol-issue-credential/src/main/scala/org/hyperledger/identus/mercury/protocol/issuecredential/OfferCredential.scala, mercury/protocol-issue-credential/src/main/scala/org/hyperledger/identus/mercury/protocol/issuecredential/RequestCredential.scala, mercury/protocol-issue-credential/src/test/scala/org/hyperledger/identus/mercury/protocol/anotherclasspath/UtilsCredentialSpec.scala, mercury/protocol-revocation-notification/src/main/scala/org/hyperledger/identus/mercury/protocol/revocationnotificaiton/RevocationNotification.scala, pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/repository/CredentialRepositorySpecSuite.scala, pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImplSpec.scala, pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/PresentationServiceSpec.scala
Integrate ZIO failures and defects ADR in DID Registrar Controller and Mercury
Related with the tickets ATL-6831 and parcial for ATL-7257
=> feat: Integrate ZIO failures and defects ADR in DID Registrar Controller and Mercury

.github/workflows/auto-merge.yml, examples/st-oid4vci/demo.py
=> ci: fix auto-merge.yml file [skip ci]

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/MainApp.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/sql/Migrations.scala, connect/sql-doobie/src/main/scala/org/hyperledger/identus/connect/sql/repository/Migrations.scala, pollux/sql-doobie/src/main/scala/org/hyperledger/identus/pollux/sql/repository/Migrations.scala
Migration script self-healing in case of renaming of the files 
Flymigration to handle renaming with auto repair
=> fix: migrate and repair in case of renaming issues

.github/CODEOWNERS
- Remove Todor's account
- Add Tim's account
- Add `infrastructure` directory filter
=> chore: update codeowners files [skip ci]

infrastructure/charts/agent/templates/podmonitor-postgresql.yaml, infrastructure/charts/agent/templates/postgresql.yaml, infrastructure/charts/agent/values.yaml
Opt-in prometheus metrics for postgres.
=> feat: postgres metrics

examples/st-multi/README.md
=> style: apply linters automatic fixes

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/service/OIDCCredentialIssuerService.scala, cloud-agent/service/server/src/test/scala/org/hyperledger/identus/verification/controller/VcVerificationControllerImplSpec.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImpl.scala, pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/verification/VcVerificationServiceImplSpec.scala, pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/VerifiableCredentialPayload.scala, pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/revocation/VCStatusList2021.scala, pollux/vc-jwt/src/test/scala/org/hyperledger/identus/pollux/vc/jwt/JWTVerificationTest.scala
https://input-output.atlassian.net/browse/ATL-7659
=> feat: API Supports ValidFrom And ValidTo

pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/VerifiableCredentialPayload.scala
https://input-output.atlassian.net/browse/ATL-7659
=> feat: API Supports ValidFrom And ValidTo (PART 2)

.github/workflows/auto-merge.yml
=> ci: change auto-merge token [skip ci]

pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/VerifiableCredentialPayload.scala, pollux/vc-jwt/src/test/scala/org/hyperledger/identus/pollux/vc/jwt/JWTVerificationTest.scala
https://input-output.atlassian.net/browse/ATL-7659
=> feat: API Supports ValidFrom And ValidTo Test

build.sbt, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/jobs/BackgroundJobsHelper.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/issue/controller/IssueControllerImpl.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImpl.scala, pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/model/presentation/PresentationAttachmentSpec.scala, pollux/prex/src/main/scala/org/hyperledger/identus/pollux/prex/PresentationDefinition.scala, pollux/prex/src/main/scala/org/hyperledger/identus/pollux/prex/PresentationDefinitionValidator.scala, pollux/prex/src/test/scala/org/hyperledger/identus/pollux/prex/PresentationDefinitionValidatorSpec.scala, shared/json/src/main/scala/org/hyperledger/identus/shared/json/JsonPath.scala, shared/json/src/test/scala/org/hyperledger/identus/shared/json/JsonPathSpec.scala
=> feat: integrate json-path in presentation definition

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/PresentationStatus.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/presentproof/controller/http/PresentationStatusPage.scala
https://input-output.atlassian.net/browse/ATL-7380
=> fix: GET Requested present proof by Holder

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/oid4vci/service/OIDCCredentialIssuerService.scala, cloud-agent/service/server/src/test/scala/org/hyperledger/identus/verification/controller/VcVerificationControllerImplSpec.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImpl.scala, pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/verification/VcVerificationServiceImplSpec.scala, pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/VerifiableCredentialPayload.scala, pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/revocation/VCStatusList2021.scala, pollux/vc-jwt/src/test/scala/org/hyperledger/identus/pollux/vc/jwt/JWTVerificationTest.scala
https://input-output.atlassian.net/browse/ATL-7661
=> feat: URL or Object as Issuer

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/credentialstatus/controller/http/StatusListCredential.scala
https://input-output.atlassian.net/browse/ATL-7661
=> feat: Fix Object causing StatusList to fail

pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImpl.scala, pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImplSpec.scala, pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/DidJWT.scala
https://input-output.atlassian.net/browse/ATL-7759
=> feat: Default Object As Issuer

cloud-agent/service/server/src/test/scala/org/hyperledger/identus/verification/controller/VcVerificationControllerImplSpec.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/CredentialServiceImpl.scala, pollux/core/src/main/scala/org/hyperledger/identus/pollux/core/service/verification/VcVerificationServiceImpl.scala, pollux/core/src/test/resources/vc-schema-driver-license.json, pollux/core/src/test/resources/vc-schema-example.json, pollux/core/src/test/resources/vc-schema-personal.json, pollux/core/src/test/scala/org/hyperledger/identus/pollux/core/service/verification/VcVerificationServiceImplSpec.scala, pollux/vc-jwt/src/main/scala/org/hyperledger/identus/pollux/vc/jwt/VerifiableCredentialPayload.scala
https://input-output.atlassian.net/browse/ATL-7660
=> feat: Support Array Of Credential Schema

README.md
=> docs: Update README.md fix user documentation URL

README.md
Update README.md with credential types that are supported
=> docs: Update README.md with credential types that are supported

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/MainApp.scala
=> fix: code cleanup

tests/performance-tests/agent-performance-tests-k6/run.sh
=> refactor: download appropriate binary for k6 perf test(#1564)

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/connect/controller/ConnectionController.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/connect/controller/ConnectionControllerImpl.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/connect/controller/ConnectionEndpoints.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/connect/controller/ConnectionServerEndpoints.scala
=> feat: delete endpoint for user to delete cloud-agent connection

.github/workflows/unit-tests.yml, README.md, build.sbt, cloud-agent/service/api/http/cloud-agent-openapi-spec.yaml, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/http/DocModels.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/castor/controller/DIDRegistrarEndpoints.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/event/controller/EventEndpoints.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/iam/entity/http/EntityEndpoints.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/iam/wallet/http/WalletManagementEndpoints.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialdefinition/CredentialDefinitionRegistryEndpoints.scala, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/pollux/credentialschema/SchemaRegistryEndpoints.scala
Fix broken links on documentation site by running `linkinator`.
=> docs: fix broken links

cloud-agent/service/api/http/cloud-agent-openapi-spec.yaml, cloud-agent/service/server/src/main/scala/org/hyperledger/identus/agent/server/http/DocModels.scala
Fix broken links that appears on the documentation site.
=> fix: update broken links in oas

cloud-agent/service/server/src/main/scala/org/hyperledger/identus/LogUtils.scala
=> feat: add a timer and metric(histogram) to measure job execution duration

docs/docusaurus/sidebars.js, docs/docusaurus/vdr/manage.md
=> docs: add VDR tutorial

examples/.nickel/agent.ncl, examples/.nickel/bootstrap.ncl, examples/.nickel/caddy.ncl, examples/.nickel/db.ncl, examples/.nickel/node.ncl, examples/.nickel/root.ncl, examples/.nickel/stack.ncl, examples/.nickel/vault.ncl, examples/.nickel/versions.ncl, examples/.shared/hurl/simple_realm/01_init_realm.hurl, examples/README.md, examples/mt-keycloak-vault/README.md, examples/mt-keycloak-vault/compose.yaml, examples/mt-keycloak-vault/hurl/02_jwt_flow.hurl, examples/mt-keycloak/README.md, examples/mt-keycloak/compose.yaml, examples/mt-keycloak/hurl/02_jwt_flow.hurl, examples/mt/compose.yaml, examples/st-multi/README.md, examples/st-multi/compose.yaml, examples/st-multi/hurl/01_jwt_flow.hurl, examples/st-oid4vci/README.md, examples/st-oid4vci/compose.yaml, examples/st-vault/README.md, examples/st-vault/compose.yaml, examples/st/compose.yaml, tests/integration-tests/build.gradle.kts
https://github.com/hyperledger-identus/cloud-agent/issues/1624
This pull request updates the version used
This pull request updates the version used in the example files to ensure consistency with the latest release. Additionally, the test scripts within the examples have been revised to guarantee they execute successfully through to the completion of each flow. These changes help users run the provided examples smoothly and verify their full functionality.
=> fix: update examples to ensure they work correctly
